import type { ManagerConfig } from '../types/content';

export const managers: ManagerConfig[] = [
  {
    title: 'Home Management', table: 'home_profiles', singleton: true, description: 'Edit name, title, hero text, profile image, CV, social links, achievements and statistics.',
    fields: [
      { name: 'name', label: 'Full Name', required: true },
      { name: 'professional_title', label: 'Professional Title', required: true },
      { name: 'hero_text', label: 'Hero Text', type: 'textarea' },
      { name: 'profile_image_url', label: 'Profile Image', type: 'file', bucket: 'portfolio-assets', folder: 'profile' },
      { name: 'resume_url', label: 'Resume/CV File', type: 'file', bucket: 'documents', folder: 'cv' },
      { name: 'qr_code_url', label: 'QR Code Image', type: 'file', bucket: 'portfolio-assets', folder: 'qr' },
      { name: 'social_links', label: 'Social Media Links JSON', type: 'json' },
      { name: 'achievements', label: 'Featured Achievements JSON Array', type: 'json' },
      { name: 'stats', label: 'Professional Statistics JSON Array', type: 'json' }
    ]
  },
  { title: 'About Management', table: 'about_sections', description: 'Add, edit, or delete about content blocks.', fields: [{ name: 'title', label: 'Title' }, { name: 'body', label: 'Content', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Experience Management', table: 'experiences', description: 'Manage professional experience records.', fields: [{ name: 'role', label: 'Role' }, { name: 'organization', label: 'Organization' }, { name: 'location', label: 'Location' }, { name: 'start_date', label: 'Start Date', type: 'date' }, { name: 'end_date', label: 'End Date', type: 'date' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Education Management', table: 'education', description: 'Manage degrees and academic qualifications.', fields: [{ name: 'degree', label: 'Degree' }, { name: 'institution', label: 'Institution' }, { name: 'location', label: 'Location' }, { name: 'year', label: 'Year' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Skills Management', table: 'skills', description: 'Manage skills and skill percentages.', fields: [{ name: 'name', label: 'Skill Name' }, { name: 'category', label: 'Category' }, { name: 'percentage', label: 'Percentage', type: 'number' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Certifications Management', table: 'certifications', description: 'Upload certificate PDFs and images.', fields: [{ name: 'title', label: 'Title' }, { name: 'issuer', label: 'Issuer' }, { name: 'issue_date', label: 'Issue Date', type: 'date' }, { name: 'certificate_url', label: 'Certificate PDF', type: 'file', bucket: 'certificates', folder: 'pdfs' }, { name: 'image_url', label: 'Certificate Image', type: 'file', bucket: 'certificates', folder: 'images' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Teaching Portfolio Management', table: 'teaching_materials', description: 'Upload lesson plans, documents, and teaching resources.', fields: [{ name: 'title', label: 'Title' }, { name: 'course', label: 'Course' }, { name: 'material_type', label: 'Material Type' }, { name: 'document_url', label: 'Document', type: 'file', bucket: 'documents', folder: 'teaching' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Projects Management', table: 'projects', description: 'Manage projects, achievements, images, and documents.', fields: [{ name: 'title', label: 'Title' }, { name: 'client_or_context', label: 'Client/Context' }, { name: 'project_date', label: 'Project Date', type: 'date' }, { name: 'image_url', label: 'Image', type: 'file', bucket: 'portfolio-assets', folder: 'projects' }, { name: 'document_url', label: 'Document', type: 'file', bucket: 'documents', folder: 'projects' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Consultancy Work Management', table: 'consultancy_projects', description: 'Manage consultancy projects, reports, and images.', fields: [{ name: 'title', label: 'Title' }, { name: 'client', label: 'Client' }, { name: 'consultancy_date', label: 'Date', type: 'date' }, { name: 'report_url', label: 'Report File', type: 'file', bucket: 'documents', folder: 'consultancy' }, { name: 'image_url', label: 'Image', type: 'file', bucket: 'portfolio-assets', folder: 'consultancy' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Gallery Management', table: 'gallery_items', description: 'Upload, categorize, delete, and reorder images.', fields: [{ name: 'title', label: 'Title' }, { name: 'category', label: 'Category' }, { name: 'image_url', label: 'Image', type: 'file', bucket: 'gallery', folder: 'images' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Testimonial Management', table: 'testimonials', description: 'Manage testimonials.', fields: [{ name: 'name', label: 'Name' }, { name: 'role', label: 'Role' }, { name: 'quote', label: 'Quote', type: 'textarea' }, { name: 'image_url', label: 'Image', type: 'file', bucket: 'portfolio-assets', folder: 'testimonials' }, { name: 'sort_order', label: 'Sort Order', type: 'number' }] },
  { title: 'Contact Management', table: 'contact_info', singleton: true, description: 'Edit phone, email, website, social links, and office address.', fields: [{ name: 'phone', label: 'Phone' }, { name: 'email', label: 'Email' }, { name: 'website_url', label: 'Website URL', type: 'url' }, { name: 'office_address', label: 'Office Address', type: 'textarea' }, { name: 'social_links', label: 'Social Links JSON', type: 'json' }] }
];
